variables:
  HELM_CHART_DIR: ${CI_PROJECT_DIR}
  HELM_CHART_NAME: jhaas-portal
  HELM_CHART_CHANNEL: ${CI_COMMIT_REF_SLUG}
  HELM_CHART_VERSION: 0.1.0

stages:
  - package

helm-package:
  stage: package
  image: alpine:3.18
  script:
    - apk add --no-cache curl
    - cp values.example.yaml values.yaml
    - tar -vczf /tmp/${HELM_CHART_NAME}-${HELM_CHART_CHANNEL}-${HELM_CHART_VERSION}.tgz -C ${HELM_CHART_DIR} --exclude=./.git --exclude=./.gitignore --exclude=./.gitlab-ci.yml --exclude=./.helmignore --exclude=./values.example.yaml .
    - 'curl --request POST
        --user gitlab-ci-token:$CI_JOB_TOKEN
        --form "chart=@/tmp/${HELM_CHART_NAME}-${HELM_CHART_CHANNEL}-${HELM_CHART_VERSION}.tgz"
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${HELM_CHART_CHANNEL}/charts"'
