variables:
  HELM_CHART_DIR: ${CI_PROJECT_DIR}
  HELM_CHART_NAME: jhaas-portal
  HELM_CHART_CHANNEL: ${CI_COMMIT_REF_SLUG}

stages:
  - package

helm-package:
  stage: package
  image: alpine:3.18
  script:
    - apk add --no-cache helm
    - cp values.example.yaml values.yaml
    - mkdir -p /root/.config/helm/registry

    # Setup Secrets
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$HARBOR_HOST\":{\"username\":\"$HARBOR_USERNAME\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /root/.config/helm/registry/config.json

    # Package Helm Chart
    - tar -vczf /tmp/${HELM_CHART_NAME}-${HELM_CHART_CHANNEL}.tgz
      -C ${HELM_CHART_DIR}
      --exclude=./.git
      --exclude=./.gitignore
      --exclude=./.gitlab-ci.yml
      --exclude=./.helmignore
      --exclude=./values.example.yaml
      .

    # Push chart to GitLab
    - helm push "/tmp/${HELM_CHART_NAME}-${HELM_CHART_CHANNEL}.tgz" "oci://$CI_REGISTRY/$CI_PROJECT_PATH"


    # Push chart to harbor
    - helm push "/tmp/${HELM_CHART_NAME}-${HELM_CHART_CHANNEL}.tgz" "$HARBOR_OCI/$HARBOR_PROJECT"
