# Default values for JHaaS Portal
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  registry: harbor.computational.bio.uni-giessen.de
  username:
  password:

backend:
  image:
    registry: harbor.computational.bio.uni-giessen.de
    repository: bcf/jhaas-backend
    tag: master
    pullPolicy: IfNotPresent
  conf:
    NODE_ENV: production
    PORT: "8000"
    K8S_TF_IMAGE: harbor.computational.bio.uni-giessen.de/bcf/jhaas-tf-worker:master
    K8S_TF_NS: jhaas-portal-playground
    JH_DOMAIN:
    JWT_SECRET_A:
    JWT_SECRET_B:
    JWT_ACTIVE_SECRET:
    JWT_EXPIRY:
    JWT_REFRESH_EXPIRY:
    JWT_REFRESH_COOKIE_SECURE:

frontend:
  image:
    registry: harbor.computational.bio.uni-giessen.de
    repository: bcf/jhaas-frontend
    tag: master
    pullPolicy: IfNotPresent
  conf:
    PORT: "80"

postgres:
  # "enabled" only affects the deployment of a postgres db
  # inside the helm chart.
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  # The "conf" object is mandatory! If no db deployed by
  # this chart, you should enter data for an external db.
  conf:
    # Leave Host empty to use db deployed by helm
    POSTGRES_HOST:
    POSTGRES_PORT: "5432"
    POSTGRES_DB: jhaas-portal
    POSTGRES_USER: jhaas-portal
    POSTGRES_PASSWORD: super-secret-password-here

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

s3:
  url: "http://localhost:9000"
  access_key: "YOUR-ACCESS-KEY"
  secret_key: "YOUR-SECRET-KEY"

terraform:
  host: "localhost"
  token: "aaabbbccc"
