# Default values for JHaaS Portal
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  registry: harbor.computational.bio.uni-giessen.de
  username:
  password:

backend:
  image:
    registry: harbor.computational.bio.uni-giessen.de
    repository: bcf/jhaas_portal_backend
    tag: master
    pullPolicy: IfNotPresent
  conf:
    NODE_ENV: production
    PORT: "8000"
    K8S_TF_IMAGE:
    JH_DOMAIN:
    S3_ENDPOINT:
    S3_PORT:
    S3_SSL:
    S3_ACCESS_KEY:
    S3_SECRET_KEY:
    JWT_SECRET_A:
    JWT_SECRET_B:
    JWT_ACTIVE_SECRET:
    JWT_EXPIRY:
    JWT_REFRESH_EXPIRY:
    JWT_REFRESH_COOKIE_SECURE:

frontend:
  image:
    registry: harbor.computational.bio.uni-giessen.de
    repository: bcf/jhaas_portal_frontend
    tag: master
    pullPolicy: IfNotPresent
  conf:
    PORT: "80"

postgres:
  image:
    registry: docker.io
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  conf:
    # Leave Host empty to use db deployed by helm
    POSTGRES_HOST:
    POSTGRES_PORT: "5432"
    POSTGRES_DB: jhaas-portal
    POSTGRES_USER: jhaas-portal
    POSTGRES_PASSWORD: super-secret-password-here

ingress:
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
