apiVersion: rbac.authorization.k8s.io/v1
# Although this is a ClusterRole, it is only bound for the namespace "ns-tf-worker".
# The service account does not get any rights on other namespaces!
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.role: tf-job-spawner
  name: role-tf-job-spawner
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
