apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.service: jhaas-portal-frontend
  name: jhaas-portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      jhaas-portal.service: jhaas-portal-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        jhaas-portal.service: jhaas-portal-frontend
    spec:
      containers:
          image: git.computational.bio.uni-giessen.de:5050/it/jhaas-frontend:master
          name: jhaas-portal-frontend
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: registry-credentials
      hostname: jhaas-portal-frontend
      restartPolicy: Always
status: {}
