apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.service: jhaas-portal-backend
  name: jhaas-portal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      jhaas-portal.service: jhaas-portal-backend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        jhaas-portal.service: jhaas-portal-backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env-jhaas-portal-backend
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: env-jhaas-portal-backend
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-jhaas-portal-db
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-jhaas-portal-db
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: sec-jhaas-portal-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: sec-jhaas-portal-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: sec-jhaas-portal-db
          image: git.computational.bio.uni-giessen.de:5050/it/jhaas-backend:master
          name: jhaas-portal-backend
          ports:
            - containerPort: 8000
          resources: {}
      imagePullSecrets:
        - name: registry-credentials
      hostname: jhaas-portal-backend
      restartPolicy: Always
status: {}
