apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.service: {{ .Release.Name }}-backend
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Release.Name }}.service: {{ .Release.Name }}-backend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{ .Release.Name }}.service: {{ .Release.Name }}-backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env-{{ .Release.Name }}-backend
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: env-{{ .Release.Name }}-backend
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: env-{{ .Release.Name }}-backend
            - name: SESSION_COOKIE_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SESSION_COOKIE_SECRET
                  name: env-{{ .Release.Name }}-backend
            - name: SESSION_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: SESSION_STORAGE
                  name: env-{{ .Release.Name }}-backend
            - name: SESSION_STORAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: SESSION_STORAGE_URL
                  name: env-{{ .Release.Name }}-backend
            - name: OIDC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OIDC_ENDPOINT
                  name: env-{{ .Release.Name }}-backend
            - name: OIDC_URL_CALLBACK
              valueFrom:
                configMapKeyRef:
                  key: OIDC_URL_CALLBACK
                  name: env-{{ .Release.Name }}-backend
            - name: OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: OIDC_CLIENT_ID
                  name: env-{{ .Release.Name }}-backend
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: OIDC_CLIENT_SECRET
                  name: env-{{ .Release.Name }}-backend
            - name: AUTHENTIK_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: AUTHENTIK_API_ENDPOINT
                  name: env-{{ .Release.Name }}-backend
            - name: AUTHENTIK_API_SECRET
              valueFrom:
                configMapKeyRef:
                  key: AUTHENTIK_API_SECRET
                  name: env-{{ .Release.Name }}-backend
            - name: AUTHENTIK_JH_GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHENTIK_JH_GROUP_NAME
                  name: env-{{ .Release.Name }}-backend
            - name: RELEASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: RELEASE_NAME
                  name: env-{{ .Release.Name }}-backend
            - name: JHAAS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: JHAAS_DOMAIN
                  name: env-{{ .Release.Name }}-backend
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-{{ .Release.Name }}-db
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-{{ .Release.Name }}-db
            - name: JHAAS_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: sec-{{ .Release.Name }}-db
            - name: JHAAS_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: sec-{{ .Release.Name }}-db
            - name: JHAAS_DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: sec-{{ .Release.Name }}-db
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: env-{{ .Release.Name }}-mail
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: env-{{ .Release.Name }}-mail
            - name: MAIL_SECURE
              valueFrom:
                configMapKeyRef:
                  key: MAIL_SECURE
                  name: env-{{ .Release.Name }}-mail
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM
                  name: env-{{ .Release.Name }}-mail
            - name: MAIL_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_NAME
                  name: env-{{ .Release.Name }}-mail
            - name: MAIL_COPY_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  key: MAIL_COPY_ADDRESSES
                  name: env-{{ .Release.Name }}-mail
          image: "{{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          name: {{ .Release.Name }}-backend
          ports:
            - containerPort: {{ .Values.backend.conf.PORT }}
          resources: {}
      imagePullSecrets:
        - name: sec-{{ .Release.Name }}-registry-credentials
      hostname: {{ .Release.Name }}-backend
      restartPolicy: Always
status: {}
