apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.binding: tf-job-spawner
  name: bind-tf-job-spawner
  namespace: ns-tf-worker
subjects:
- kind: ServiceAccount
  name: acc-tf-job-spawner
roleRef:
  kind: ClusterRole
  name: role-tf-job-spawner
  apiGroup: rbac.authorization.k8s.io
