apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.binding: {{ .Release.Name }}-tf-job-spawner
  name: bind-{{ .Release.Name }}-tf-job-spawner
subjects:
- kind: ServiceAccount
  name: acc-{{ .Release.Name }}-tf-job-spawner
roleRef:
  kind: Role
  name: role-{{ .Release.Name }}-tf-job-spawner
  apiGroup: rbac.authorization.k8s.io
