apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.volume: {{ .Release.Name }}-db
  name: vol-{{ .Release.Name }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
