{{ if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.service: {{ .Release.Name }}-db
  name: sv-{{ .Release.Name }}-db
spec:
  ports:
    - name: psql
      port: {{ .Values.postgres.conf.POSTGRES_PORT }}
      targetPort: {{ .Values.postgres.conf.POSTGRES_PORT }}
      protocol: TCP
  selector:
    {{ .Release.Name }}.service: {{ .Release.Name }}-db
status:
  loadBalancer: {}
{{- end }}
