apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.service: jhaas-portal-backend
  name: sv-jhaas-portal-backend
spec:
  ports:
    - name: rest
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    jhaas-portal.service: jhaas-portal-backend
status:
  loadBalancer: {}
