apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.service: {{ .Release.Name }}-frontend
  name: sv-{{ .Release.Name }}-frontend
spec:
  ports:
    - name: http
      port: {{ .Values.frontend.conf.PORT }}
      targetPort: {{ .Values.frontend.conf.PORT }}
      protocol: TCP
  selector:
    {{ .Release.Name }}.service: {{ .Release.Name }}-frontend
status:
  loadBalancer: {}
