apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.service: jhaas-portal-frontend
  name: sv-jhaas-portal-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    jhaas-portal.service: jhaas-portal-frontend
status:
  loadBalancer: {}
