{{ if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.service: {{ .Release.Name }}-redis
  name: sv-{{ .Release.Name }}-redis
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
  selector:
    {{ .Release.Name }}.service: {{ .Release.Name }}-redis
status:
  loadBalancer: {}
{{- end }}
