apiVersion: v1
data:
  terraform.secret: {{ template "tfConfig" . }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-tf-conf
  name: sec-{{ .Release.Name }}-tf-conf
type: Opaque
