{{ if .Values.jhaas.create_kubeconf_secret -}}
apiVersion: v1
data:
{{ (.Files.Glob "data/*.{secret,yaml}").AsSecrets | indent 2 }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-cloud-kubeconfig
  name: sec-{{ .Release.Name }}-cloud-kubeconfig
type: Opaque
{{- end }}
