apiVersion: v1
data:
  minio.secret: {{ template "s3Config" . }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-s3-conf
  name: sec-{{ .Release.Name }}-s3-conf
type: Opaque
