apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-registry-credentials
  name: sec-{{ .Release.Name }}-registry-credentials
type: kubernetes.io/dockerconfigjson
