apiVersion: v1
data:
  # jhaas-portal
  POSTGRES_DB: amhhYXMtcG9ydGFs
  # jhaas-portal
  POSTGRES_USER: amhhYXMtcG9ydGFs
  # you-better-change-me
  POSTGRES_PASSWORD: eW91LWJldHRlci1jaGFuZ2UtbWU=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.secret: jhaas-portal-db
  name: sec-jhaas-portal-db
type: Opaque
