apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    jhaas-portal.secret: jhaas-portal-registry-credentials
  name: sec-jhaas-portal-registry-credentials
type: kubernetes.io/dockerconfigjson
