apiVersion: v1
data:
  access_key: {{ .Values.s3_data.access_key | b64enc | quote }}
  secret_key: {{ .Values.s3_data.secret_key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-s3-data-conf
  name: sec-{{ .Release.Name }}-s3-data-conf
type: Opaque
