apiVersion: v1
data:
  minio.secret: {{ template "s3Config" . }}
  access_key: {{ .Values.s3.access_key | b64enc | quote }}
  secret_key: {{ .Values.s3.secret_key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-s3-conf
  name: sec-{{ .Release.Name }}-s3-conf
type: Opaque
