apiVersion: v1
data:
  minio.secret: {{ template "s3Config" . }}
  url: {{ printf "%s://%s:%s" (.Values.s3.ssl | ternary "https" "http") .Values.s3.host .Values.s3.port | b64enc | quote }}
  access_key: {{ .Values.s3.access_key | b64enc | quote }}
  secret_key: {{ .Values.s3.secret_key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-s3-conf
  name: sec-{{ .Release.Name }}-s3-conf
type: Opaque
