apiVersion: v1
data:
  MAIL_USER: {{ .Values.mail.user | b64enc | quote }}
  MAIL_PASS: {{ .Values.mail.pass | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-mail
  name: sec-{{ .Release.Name }}-mail
type: Opaque
