{{- range .Values.imageCredentials }}
apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password (printf "%s:%s" .username .password | b64enc) | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ $.Release.Name }}.secret: {{ $.Release.Name }}-{{ .name }}-registry-credentials
  name: sec-{{ $.Release.Name }}-{{ .name }}-registry-credentials
type: kubernetes.io/dockerconfigjson
---
{{- end }}
