apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgres.conf.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.conf.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.conf.POSTGRES_PASSWORD | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    {{ .Release.Name }}.secret: {{ .Release.Name }}-db
  name: sec-{{ .Release.Name }}-db
type: Opaque
