{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-ingress
  labels:
    {{ .Release.Name }}.service: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.ingress.tls.issuer  }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else }}
      secretName: sec-{{ .Release.Name }}-tls
      {{- end }}
  {{- end }}

  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/(.*)$
        pathType: Prefix
        backend:
          service:
            name: sv-{{ .Release.Name }}-backend
            port:
              number: {{ .Values.backend.conf.PORT }}
      - path: /(.*)$
        pathType: Prefix
        backend:
          service:
            name: sv-{{ .Release.Name }}-frontend
            port:
              number: {{ .Values.frontend.conf.PORT }}
      {{- if .Values.docs.enabled }}
      - path: {{ .Values.docs.conf.PATH }}/(.*)$
        pathType: Prefix
        backend:
          service:
            name: sv-{{ .Release.Name }}-docs
            port:
              number: {{ .Values.docs.conf.PORT }}
      {{- end }}

{{- end }}
